import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Report {
    private String reportID;
    private LocalDateTime generatedDate;
    private CareerStaff generatedBy;
    private Filter filterCriteria;
    private List<InternshipOpportunity> internshipList;

    public Report(Filter filterCriteria, CareerStaff generatedBy) {
        this.reportID = UUID.randomUUID().toString();
        this.generatedDate = LocalDateTime.now();
        this.filterCriteria = filterCriteria;
        this.generatedBy = generatedBy;
        this.internshipList = fetchInternshipsBasedOnFilter(filterCriteria);
    }

    private List<InternshipOpportunity> fetchInternshipsBasedOnFilter(Filter filter) {
        // TODO: Replace with actual data source or repository
        List<InternshipOpportunity> allInternships = InternshipRepository.getAllInternships(); // placeholder
        List<InternshipOpportunity> filtered = new ArrayList<>();

        for (InternshipOpportunity opp : allInternships) {
            boolean matches = true;

            if (filter.getLevel() != null && opp.getLevel() != filter.getLevel()) {
                matches = false;
            }
            if (filter.getPreferredMajor() != null && !filter.getPreferredMajor().equalsIgnoreCase(opp.getPrefMajor())) {
                matches = false;
            }
            if (filter.getStatus() != null && opp.getStatus() != filter.getStatus()) {
                matches = false;
            }
            if (opp.getVisibility() != filter.isVisibility()) {
                matches = false;
            }
            if (filter.getRepresentative() != null && opp.getRep() != filter.getRepresentative()) {
                matches = false;
            }
            if (filter.getNumOfSlots() > 0 && opp.getNumOfSlots() != filter.getNumOfSlots()) {
                matches = false;
            }

            // Optional: filter by dates if needed (dates are strings in "yyyy-MM-dd" format)
            // You could convert to LocalDate for comparison here

            if (matches) {
                filtered.add(opp);
            }
        }

        return filtered;
    }

    public void display() {
        System.out.println("========== Internship Report ==========");
        System.out.println("Report ID: " + reportID);
        System.out.println("Generated Date: " + generatedDate);
        System.out.println("Generated By: " + (generatedBy != null ? generatedBy.getName() : "N/A"));

        System.out.println("\n----- Filter Criteria -----");
        System.out.println("Internship Level: " + valueOrNA(filterCriteria.getLevel()));
        System.out.println("Preferred Major: " + valueOrNA(filterCriteria.getPreferredMajor()));
        System.out.println("Application Open Date: " + valueOrNA(filterCriteria.getApplicationOpenDate()));
        System.out.println("Application Close Date: " + valueOrNA(filterCriteria.getApplicationCloseDate()));
        System.out.println("Company Representative: " +
                (filterCriteria.getRepresentative() != null ? filterCriteria.getRepresentative().getName() : "N/A"));
        System.out.println("Number of Slots: " + valueOrNA(filterCriteria.getNumOfSlots()));
        System.out.println("Internship Status: " + valueOrNA(filterCriteria.getStatus()));
        System.out.println("Visibility: " + filterCriteria.isVisibility());

        System.out.println("\n----- Internship Opportunities -----");
        if (internshipList == null || internshipList.isEmpty()) {
            System.out.println("No internship opportunities found for the selected criteria.");
        } else {
            for (InternshipOpportunity opp : internshipList) {
                System.out.println("Title: " + valueOrNA(opp.getTitle()));
                System.out.println("Company: " + valueOrNA(opp.getRep() != null ? opp.getRep().getCompany() : null));
                System.out.println("Level: " + valueOrNA(opp.getLevel()));
                System.out.println("Preferred Major: " + valueOrNA(opp.getPrefMajor()));
                System.out.println("Application Dates: " + valueOrNA(opp.getOpenDate()) + " to " + valueOrNA(opp.getCloseDate()));
                System.out.println("Number of Slots: " + valueOrNA(opp.getNumOfSlots()));
                System.out.println("Status: " + valueOrNA(opp.getStatus()));
                System.out.println("Visibility: " + opp.getVisibility());
                System.out.println("--------------------------------------");
            }
        }
        System.out.println("======================================");
    }

    private String valueOrNA(Object value) {
        return value != null ? value.toString() : "N/A";
    }
}
