package edu.ntu.ccds.sc2002.internship.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Report {
    private String reportId;
    private LocalDateTime generatedDate;
    private CareerStaff generatedBy;
    private Filter filterCriteria;
    private List<InternshipOpportunity> internshipList;
    private List<InternshipOpportunity> internshipListFiltered;

    public Report(Filter filterCriteria, CareerStaff generatedBy, List<InternshipOpportunity> internshipList) {
        this.reportId = UUID.randomUUID().toString();
        this.generatedDate = LocalDateTime.now();
        this.filterCriteria = filterCriteria;
        this.generatedBy = generatedBy;
        this.internshipList = internshipList;
        this.internshipListFiltered = fetchInternshipsBasedOnFilter(filterCriteria);
    }

    private List<InternshipOpportunity> fetchInternshipsBasedOnFilter(Filter filter) {
        List<InternshipOpportunity> all = this.internshipList;
        List<InternshipOpportunity> filtered = new ArrayList<>();

        for (InternshipOpportunity opp : all) {
            boolean matches = true;

            if (filter.getLevel() != null &&
                    opp.getLevel() != filter.getLevel()) {
                matches = false;
            }

            if (filter.getPreferredMajor() != null &&
                    !filter.getPreferredMajor().equalsIgnoreCase(opp.getPrefMajor())) {
                matches = false;
            }

            if (filter.getStatus() != null &&
                    opp.getStatus() != filter.getStatus()) {
                matches = false;
            }

            if (filter.isVisibility() != null &&
                    opp.getVisibility() != filter.isVisibility()) {
                matches = false;
            }

            if (filter.getRepName() != null &&
                    !filter.getRepName().equalsIgnoreCase(opp.getRep().getName())) {
                matches = false;
            }

            if (filter.getClosingDate() != null &&
                    !filter.getClosingDate().equalsIgnoreCase(opp.getCloseDate())) {
                matches = false;
            }

            if (matches)
                filtered.add(opp);
        }

        return filtered;
    }

    /**
     * Generates formatted report as a string.
     * MODEL LAYER: Returns data instead of printing to console.
     */
    public String generateReport() {
        StringBuilder sb = new StringBuilder();

        sb.append("========== Internship Report ==========\n");
        sb.append("Report ID: ").append(reportId).append("\n");
        sb.append("Generated Date: ").append(generatedDate).append("\n");
        sb.append("Generated By: ").append(generatedBy != null ? generatedBy.getName() : "N/A").append("\n");

        sb.append("\n----- Filter Criteria -----\n");
        sb.append("Internship Level: ").append(valueOrNA(filterCriteria.getLevel())).append("\n");
        sb.append("Preferred Major: ").append(valueOrNA(filterCriteria.getPreferredMajor())).append("\n");
        sb.append("Company Representative: ")
                .append(filterCriteria.getRepName() != null ? filterCriteria.getRepName()
                        : "N/A")
                .append("\n");
        sb.append("Internship Status: ").append(valueOrNA(filterCriteria.getStatus())).append("\n");
        sb.append("Closing Date: ").append(valueOrNA(filterCriteria.getClosingDate())).append("\n");
        sb.append("Visibility: ").append(filterCriteria.isVisibility()).append("\n");

        sb.append("\n----- Internship Opportunities -----\n");
        if (internshipList == null || internshipList.isEmpty()) {
            sb.append("No internship opportunities found for the selected criteria.\n");
        } else {
            for (InternshipOpportunity opp : internshipListFiltered) {
                sb.append("Title: ").append(valueOrNA(opp.getTitle())).append("\n");
                sb.append("Representative: ").append(valueOrNA(opp.getRep().getName())).append("\n");
                sb.append("Level: ").append(valueOrNA(opp.getLevel())).append("\n");
                sb.append("Preferred Major: ").append(valueOrNA(opp.getPrefMajor())).append("\n");
                sb.append("Application Dates: ").append(valueOrNA(opp.getOpenDate()))
                        .append(" to ").append(valueOrNA(opp.getCloseDate())).append("\n");
                sb.append("Number of Slots: ").append(valueOrNA(opp.getNumOfSlots())).append("\n");
                sb.append("Status: ").append(valueOrNA(opp.getStatus())).append("\n");
                sb.append("Visibility: ").append(opp.getVisibility()).append("\n");
                sb.append("--------------------------------------\n");
            }
        }
        sb.append("======================================\n");

        return sb.toString();
    }

    private String valueOrNA(Object value) {
        return value != null ? value.toString() : "N/A";
    }
}
